spring:
  datasource:
    url: jdbc:mysql://localhost/DIO_Banco
    username: usersql
    password: FreeFallliaf@#!1
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true